### ISSUE TITLE
Failed to determine erroneous kmer threshold. Threshold set to: 37?

### ISSUE THREAD

**Issue by lychen83** [quxiaojian/OGA#1]
Hi Qu,

I am running the OGA to assemble my cp genome. When running the OGA.pl, I found some warnings at the end of the job:
_=== Error correction and assembling warnings:
 * 0:00:09.322    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 30
 * 0:00:01.859    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
 * 0:00:05.620    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 37
 * 0:00:04.324    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 22_

Could you kindly explain what's does this mean, and how to resolve this problem?

I appreciate your help.

Best regards,

Lingyun

**Comment by quxiaojian** [comment]
> Hi Qu,
> 
> I am running the OGA to assemble my cp genome. When running the OGA.pl, I found some warnings at the end of the job:
> _=== Error correction and assembling warnings:
> 
> * 0:00:09.322    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 30
> * 0:00:01.859    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 218)   Too many erroneous kmers, the estimates might be unreliable
> * 0:00:05.620    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 37
> * 0:00:04.324    64M / 8G    WARN    General                 (kmer_coverage_model.cpp   : 366)   Failed to determine erroneous kmer threshold. Threshold set to: 22_
> 
> Could you kindly explain what's does this mean, and how to resolve this problem?
> 
> I appreciate your help.
> 
> Best regards,
> 
> Lingyun

It's the response of Spades. If you are interested in what it means, you can search manual of Spades.
I think it may be due to reads quality. In addition, -e n is strongly recommend. Third, -k 61,81,101,121 is enough, improper kmer setting maybe another factor.
However, if the result is good and not be influenced, you can neglect this warning released by Spades.
Hope it can help you.
